export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'

export const VENDOR_LIST_BY_SHOP_REQUEST = 'VENDOR_LIST_BY_SHOP_REQUEST'
export const VENDOR_LIST_BY_SHOP_SUCCESS = 'VENDOR_LIST_BY_SHOP_SUCCESS'
export const VENDOR_LIST_BY_SHOP_FAIL = 'VENDOR_LIST_BY_SHOP_FAIL'

export const VENDOR_LIST_BY_VENDOR_REQUEST = 'VENDOR_LIST_BY_VENDOR_REQUEST'
export const VENDOR_LIST_BY_VENDOR_SUCCESS = 'VENDOR_LIST_BY_VENDOR_SUCCESS'
export const VENDOR_LIST_BY_VENDOR_FAIL = 'VENDOR_LIST_BY_VENDOR_FAIL'

export const VENDOR_LIST_BY_CATEGORY_REQUEST = 'VENDOR_LIST_BY_CATEGORY_REQUEST'
export const VENDOR_LIST_BY_CATEGORY_SUCCESS = 'VENDOR_LIST_BY_CATEGORY_SUCCESS'
export const VENDOR_LIST_BY_CATEGORY_FAIL = 'VENDOR_LIST_BY_CATEGORY_FAIL'

export const VENDOR_DETAILS_REQUEST = 'VENDOR_DETAILS_REQUEST'
export const VENDOR_DETAILS_SUCCESS = 'VENDOR_DETAILS_SUCCESS'
export const VENDOR_DETAILS_FAIL = 'VENDOR_DETAILS_FAIL'

export const VENDOR_DELETE_REQUEST = 'VENDOR_DELETE_REQUEST'
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS'
export const VENDOR_DELETE_FAIL = 'VENDOR_DELETE_FAIL'

export const VENDOR_CREATE_REQUEST = 'VENDOR_CREATE_REQUEST'
export const VENDOR_CREATE_SUCCESS = 'VENDOR_CREATE_SUCCESS'
export const VENDOR_CREATE_FAIL = 'VENDOR_CREATE_FAIL'
export const VENDOR_CREATE_RESET = 'VENDOR_CREATE_RESET'

export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST'
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS'
export const VENDOR_UPDATE_FAIL = 'VENDOR_UPDATE_FAIL'
export const VENDOR_UPDATE_RESET = 'VENDOR_UPDATE_RESET'

export const VENDOR_CREATE_REVIEW_REQUEST = 'VENDOR_CREATE_REVIEW_REQUEST'
export const VENDOR_CREATE_REVIEW_SUCCESS = 'VENDOR_CREATE_REVIEW_SUCCESS'
export const VENDOR_CREATE_REVIEW_FAIL = 'VENDOR_CREATE_REVIEW_FAIL'
export const VENDOR_CREATE_REVIEW_RESET = 'VENDOR_CREATE_REVIEW_RESET'

export const VENDOR_TOP_REQUEST = 'VENDOR_TOP_REQUEST'
export const VENDOR_TOP_SUCCESS = 'VENDOR_TOP_SUCCESS'
export const VENDOR_TOP_FAIL = 'VENDOR_TOP_FAIL'
